# Env
LOGGER_NAME = 'OLYMPUS_LOGGER_NAME'
FILE_LOGGER_ENV = 'OLYMPUS_LOG_TO_FILE'
STDOUT_LOGGER_ENV = 'OLYMPUS_LOG_TO_STDOUT'
FILE_PATH_ENV = 'OLYMPUS_LOG_FILE_PATH'

# Const
DEFAULT_FILE_PATH = './logs'
